### ISSUE TITLE
Thank you for your contribution. Can you provide the source code in the future?

### ISSUE THREAD

**Issue by youzi260** [VITA-Group/MM3DGS-SLAM#1]
Thank you for your contribution. Can you provide the source code in the future?

**Comment by Neel1302** [comment]
Hi, thanks for your interest in our work. We will release our code publicly and are currently working on some clean up on our end while our paper is under review. We will update this page shortly with the source code. Stay tuned.

**Comment by Neel1302** [comment]
We have now released the [code](https://github.com/VITA-Group/MM3DGS-SLAM) and [dataset](https://huggingface.co/datasets/neel1302/UT-MM).
