### ISSUE TITLE
代码更新

### ISSUE THREAD

**Issue by jerryjifjsdbf** [VITA-Group/MM3DGS-SLAM#3]
请问代码啥时候更新

**Comment by hiyyg** [comment]
+1

**Comment by Neel1302** [comment]
Hi, thanks for your interest in our work. We will release our code publicly and are currently working on some clean up on our end while our paper is under review. We will update this page shortly with the source code. Stay tuned.

**Comment by Neel1302** [comment]
We have now released the [code](https://github.com/VITA-Group/MM3DGS-SLAM) and [dataset](https://huggingface.co/datasets/neel1302/UT-MM).
