### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by haoming-Yu** [VITA-Group/MM3DGS-SLAM#6]
Could you please upload the accessible UTMM datasets without installing ROS? ROS is not compatible with ubuntu24.04 for most cases. Uploading a datasets which can be used directly will definitely make it easier to replicate.

**Comment by jcliu979** [comment]
It should be possible to access the datasets, as you can read the rosbags with the python rosbag library in ```scripts/bag2data.py```. Just comment out the section that uses anything from ```import tf``` and use the text file in ```tf/tf.txt```, as the transformations are static.

**Comment by Neel1302** [comment]
@haoming-Yu, in addition to @jcliu979's suggestion, you can also run ROS Noetic via docker on Ubuntu. See here: https://wiki.ros.org/docker/Tutorials/Docker.

You can run the following commands the Ubuntu terminal: 

Step 1 : Install docker on Ubuntu:
```
sudo apt-get install docker-ce docker-ce-cli containerd.io 
```

Step 2 : Pull the ROS Noetic docker image :
```
docker pull ros:noetic
```

Step 3 : Start a new docker container running ROS Noetic and open bash:
```
docker run -it ros:noetic /bin/bash
```

**Comment by haoming-Yu** [comment]
Thank you guys very much~
