### ISSUE TITLE
Error with "self.midas = torch.hub.load("intel-isl/MiDaS", "DPT_Hybrid", force_reload=True)"

### ISSUE THREAD

**Issue by shuttworth** [VITA-Group/MM3DGS-SLAM#7]
File "/home/kkk/anaconda3/envs/mm3dgs/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response    

While downloading dpt.pt and others, network always is bad,even with VPN.
And local dpt_hybrid_384.pt could not perform well.

**Comment by codeysun** [comment]
Hi there, unfortunately I have tried and cannot reproduce this issue. Judging from the error, it looks like a network issue. 

If others encounter this issue, please post here.
