### ISSUE TITLE
how to adjust the iteration number 

### ISSUE THREAD

**Issue by TomZhongJie** [VITA-Group/MM3DGS-SLAM#8]
The iteration number of each scene in UTMM_Dataset is fixed, how do I adjust the iteration number? Changing the iteration in UTMM.yml will not help, but also cause an error when running

**Comment by codeysun** [comment]
To change the number of optimization iterations for tracking/mapping, look at `tracking/iters` or `mapping/iters`.

`iteration` is for loading a checkpoint, and requires that an existing saved output already exists in the output directory.
